[project]
name = "frontend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dash>=4.4.1",
    "dash-bootstrap-components>=2.0.4",
    "dash-core-components>=2.0.0",
    "httpx>=0.28.1",
    "numpy>=2.5.3",
    "pandas>=3.0.5",
    "plotly>=7.1.0",
    "dash-ag-grid>=35.3.0",
    "loguru>=0.7.3",
]

[dependency-groups]
dev = [
    "ruff>=0.16.7",
]

[tool.uv]
package = true

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
frontend = "dashboard.app:create_app"

[tool.ruff]
line-length = 88
indent-width = 4
